apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: o6vt3z3ax-go 
  janus-idp.io/tekton: o6vt3z3ax-go
  backstage.io/kubernetes-id: o6vt3z3ax-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: o6vt3z3ax-go
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml